// 站点构建前处理：拷贝附件与文档、注入锚点、生成侧边栏数据
import { readFileSync, writeFileSync, mkdirSync, cpSync, existsSync, rmSync } from 'node:fs'
import { dirname, join } from 'node:path'

const ROOT = process.cwd()
const DOCS = join(ROOT, 'docs')
const ensure = p => mkdirSync(dirname(p), { recursive: true })
const plainTitle = s => s.replace(/<[^>]+>/g, '').trim()

// 条目徽标规则（按标题关键字，中英通用）
const BADGE_RULES = [
  { re: /无效的伪造信息|Invalid forged info/i, badge: { text: '误报', type: 'warning' } },
  { re: /zygote test|App Zygote|Zygote 存在异常|Zygote Anomaly/i, badge: { text: '误报', type: 'warning' } },
  { re: /Tampered Attestation Key|Tampered Attention/i, badge: { text: '含误报', type: 'warning' } },
  { re: /Abnormal Environment|异常环境/i, badge: { text: '侧信道', type: 'tip' } },
  { re: /检测SELinux Policy|Suspicious SELinux Policy/i, badge: { text: '常见', type: 'info' } },
  { re: /mountinfo|Inconsistent mount|Mount Anomaly|挂载异常|不一致的挂载/i, badge: { text: '常见', type: 'info' } },
  { re: /Current-app-root-domain-trace|设备获取 Root|ROOT access obtained/i, badge: { text: '需 Root', type: 'info' } },
  { re: /发现APatch|APatch SuperKey/i, badge: { text: '暂无解', type: 'danger' } }
]
const badgeFor = t => {
  const hit = BADGE_RULES.find(r => r.re.test(t))
  return hit ? hit.badge : undefined
}

// 分类图标（按出现顺序套用；中英各 8 组）
const GROUP_ICON = ['📖', '🧭', '🔐', '🔑', '🗂️', '🧪', '⚙️', '📎']

// 1) 附件：File/ → docs/public/File/（站点里 /File/... 链接可直接访问）
rmSync(join(DOCS, 'public', 'File'), { recursive: true, force: true })
if (existsSync(join(ROOT, 'File'))) cpSync(join(ROOT, 'File'), join(DOCS, 'public', 'File'), { recursive: true })

// 2) 解析 Markdown：## 分类 + ### 条目（标准标题层级），生成侧边栏数据
function vpSlug(str) {
  return String(str).normalize('NFKD')
    .replace(/[\u0300-\u036F]/g, '')
    .replace(/[\u0000-\u001f]/g, '')
    .replace(/[\s~`!@#$%^&*()\-_+=[\]{}|\\;:"'“”‘’<>,.?/]+/g, '-')
    .replace(/-{2,}/g, '-').replace(/^-+|-+$/g, '').toLowerCase()
}

function convert(md, lang) {
  const lines = md.split('\n')
  const groups = []
  let current = null
  const used = new Map()
  for (const line of lines) {
    const h2 = line.match(/^##\s+(.+?)\s*$/)
    if (h2) {
      const name = plainTitle(h2[1])
      current = (['目录', 'Table of Contents', '声明', 'Disclaimer', '检测项正文', 'Detection Items'].includes(name))
        ? { skip: true }
        : { text: `${GROUP_ICON[groups.filter(g => g.items).length] || '•'} ${name}`, collapsed: true, items: [] }
      groups.push(current)
      continue
    }
    const h3 = line.match(/^###\s+(.+?)\s*$/)
    if (h3 && current && !current.skip) {
      const title = plainTitle(h3[1])
      let slug = vpSlug(title)
      const n = (used.get(slug) || 0)
      used.set(slug, n + 1)
      if (n) slug = `${slug}-${n}`         // 与 markdown-it-anchor 的去重规则一致
      current.items.push({ text: title, link: `/${lang}/#${slug}` })
    }
  }
  // 站点里把附件指向渲染页；并转义裸尖括号（如 "value < 1000"），避免 Vue 模板解析报错
  const text = md
    .replace(/\(\/File\/Doc\/thanks\.md\)/g, '(/thanks)')
    .replace(/<(?=\s|\d|=|\.|,|%|\))/g, '&lt;')
  return { text, sidebar: groups.filter(g => g.items && g.items.length) }
}

// 2.5) 生成站点页面
const zh = convert(readFileSync(join(ROOT, 'language/answer_zh.md'), 'utf8'), 'zh')
const en = convert(readFileSync(join(ROOT, 'language/answer_en.md'), 'utf8'), 'en')
ensure(join(DOCS, 'zh/index.md')); writeFileSync(join(DOCS, 'zh/index.md'), zh.text, 'utf8')
ensure(join(DOCS, 'en/index.md')); writeFileSync(join(DOCS, 'en/index.md'), en.text, 'utf8')

// 3) 致谢清单渲染页
if (existsSync(join(ROOT, 'File/Doc/thanks.md'))) {
  ensure(join(DOCS, 'thanks.md'))
  writeFileSync(join(DOCS, 'thanks.md'), readFileSync(join(ROOT, 'File/Doc/thanks.md'), 'utf8'), 'utf8')
}

// 4) 侧边栏数据（生成 TS 模块，config 直接 import）
const ts = '// AUTO-GENERATED by scripts/prepare.mjs — do not edit\nexport default '
  + JSON.stringify({ zh: zh.sidebar, en: en.sidebar }, null, 2) + ' as const\n'
ensure(join(DOCS, '.vitepress/data/sidebar.ts')); writeFileSync(join(DOCS, '.vitepress/data/sidebar.ts'), ts, 'utf8')

const n = s => s.reduce((a, g) => a + g.items.length, 0)
console.log(`[prepare] zh: ${zh.sidebar.length} groups / ${n(zh.sidebar)} items | en: ${en.sidebar.length} groups / ${n(en.sidebar)} items`)
