// 站点构建前处理：拷贝附件与文档、注入锚点、生成侧边栏数据
import { readFileSync, writeFileSync, mkdirSync, cpSync, existsSync, rmSync } from 'node:fs'
import { dirname, join } from 'node:path'

const ROOT = process.cwd()
const DOCS = join(ROOT, 'docs')
const ensure = p => mkdirSync(dirname(p), { recursive: true })
const plainTitle = s => s.replace(/<[^>]+>/g, '').trim()

// 1) 附件：File/ → docs/public/File/（站点里 /File/... 链接可直接访问）
rmSync(join(DOCS, 'public', 'File'), { recursive: true, force: true })
if (existsSync(join(ROOT, 'File'))) cpSync(join(ROOT, 'File'), join(DOCS, 'public', 'File'), { recursive: true })

// 2) 解析 Markdown：按 ## 分类聚合 <details> 条目，注入锚点
function convert(md, lang) {
  const lines = md.split('\n')
  const out = []
  const groups = []
  let current = null
  for (const line of lines) {
    const h2 = line.match(/^##\s+(.+?)\s*$/)
    if (h2) {
      const name = plainTitle(h2[1])
      current = (['目录', 'Table of Contents', '声明', 'Disclaimer'].includes(name))
        ? { skip: true }
        : { text: name, collapsed: true, items: [] }
      groups.push(current)
      out.push(line)
      continue
    }
    const sum = line.match(/^<summary>(.*?)<\/summary>\s*$/)
    if (sum && current && !current.skip) {
      const title = plainTitle(sum[1])
      if (title && title !== '目录' && !title.includes('声明') && !title.includes('Disclaimer')) {
        const id = `item-${groups.length}-${current.items.length}`
        current.items.push({ text: title, link: `/${lang}/#${id}` })
        out.push(`<a id="${id}"></a>`)
      }
    }
    out.push(line)
  }
  // 站点里把附件指向渲染页
  const text = out.join('\n').replace(/\(\/File\/Doc\/thanks\.md\)/g, '(/thanks)')
  return { text, sidebar: groups.filter(g => g.items && g.items.length) }
}

const zh = convert(readFileSync(join(ROOT, 'language/answer_zh.md'), 'utf8'), 'zh')
const en = convert(readFileSync(join(ROOT, 'language/answer_en.md'), 'utf8'), 'en')
ensure(join(DOCS, 'zh/index.md')); writeFileSync(join(DOCS, 'zh/index.md'), zh.text, 'utf8')
ensure(join(DOCS, 'en/index.md')); writeFileSync(join(DOCS, 'en/index.md'), en.text, 'utf8')

// 3) 致谢清单渲染页
if (existsSync(join(ROOT, 'File/Doc/thanks.md'))) {
  ensure(join(DOCS, 'thanks.md'))
  writeFileSync(join(DOCS, 'thanks.md'), readFileSync(join(ROOT, 'File/Doc/thanks.md'), 'utf8'), 'utf8')
}

// 4) 侧边栏数据（生成 TS 模块，config 直接 import）
const ts = '// AUTO-GENERATED by scripts/prepare.mjs — do not edit\nexport default '
  + JSON.stringify({ zh: zh.sidebar, en: en.sidebar }, null, 2) + ' as const\n'
ensure(join(DOCS, '.vitepress/data/sidebar.ts')); writeFileSync(join(DOCS, '.vitepress/data/sidebar.ts'), ts, 'utf8')

const n = s => s.reduce((a, g) => a + g.items.length, 0)
console.log(`[prepare] zh: ${zh.sidebar.length} groups / ${n(zh.sidebar)} items | en: ${en.sidebar.length} groups / ${n(en.sidebar)} items`)
